services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $exportPaths: '%wexample_symfony_pseudocode.paths%'
            $defaultOutputDir: '%wexample_symfony_pseudocode.output_dir%'

    Wexample\SymfonyPseudocode\:
        resource: '../../{Command,Service}'
        tags: ['controller.service_arguments']
